# Generated by Django 4.0.8 on 2022-11-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indication",
            name="drug",
        ),
        migrations.AddField(
            model_name="indication",
            name="drug",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indications",
                to="api.drug",
            ),
            preserve_default=False,
        ),
    ]
