# Generated by Django 4.0.8 on 2022-11-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_indication_drug_indication_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indication',
            name='slug',
        ),
        migrations.AlterField(
            model_name='dosage',
            name='adult_freq',
            field=models.IntegerField(help_text='per day'),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='adult_per_dose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='weight_based_per_dose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='renaldose',
            name='adult_freq',
            field=models.IntegerField(help_text='per day'),
        ),
        migrations.AlterField(
            model_name='renaldose',
            name='adult_per_dose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='renaldose',
            name='weight_based_per_dose',
            field=models.FloatField(),
        ),
    ]
