# Generated by Django 4.0.8 on 2022-11-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_indication_slug_alter_dosage_adult_freq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='renal_comments',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='RenalDose',
        ),
    ]
